// <auto-generated />
using System;
using CarRentalCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRentalCore.Migrations
{
    [DbContext(typeof(PetRentalContext))]
    [Migration("20210208102938_fix accessory table realtion to rental")]
    partial class fixaccessorytablerealtiontorental
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("CarRentalCore.Model.Accessorry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AccessoryTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PetTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessoryTypeId");

                    b.ToTable("Accessorry");
                });

            modelBuilder.Entity("CarRentalCore.Model.AccessoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("AccessoryType");
                });

            modelBuilder.Entity("CarRentalCore.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("CarRentalCore.Model.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("AccessorryId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccessorryId");

                    b.HasIndex("ClientId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("CarRentalCore.Model.Accessorry", b =>
                {
                    b.HasOne("CarRentalCore.Model.AccessoryType", "AccessoryType")
                        .WithMany("Accessorries")
                        .HasForeignKey("AccessoryTypeId");

                    b.Navigation("AccessoryType");
                });

            modelBuilder.Entity("CarRentalCore.Model.Rental", b =>
                {
                    b.HasOne("CarRentalCore.Model.Accessorry", "Accessorry")
                        .WithMany("Rentals")
                        .HasForeignKey("AccessorryId");

                    b.HasOne("CarRentalCore.Model.Client", "Client")
                        .WithMany("Rentals")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessorry");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("CarRentalCore.Model.Accessorry", b =>
                {
                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRentalCore.Model.AccessoryType", b =>
                {
                    b.Navigation("Accessorries");
                });

            modelBuilder.Entity("CarRentalCore.Model.Client", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
